import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  
  basicSidebar: [
    {type: 'autogenerated', dirName: 'basic'},
    {type: 'autogenerated', dirName: 'scene'}
  ],
};

export default sidebars;
